import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.management.DescriptorKey;

@DynamoDBTable(tableName = "Test")
public class TestModel {
    private String id = null;
    private String personName = null;
    private int age = 0;
    private String owner = null;

    @DynamoDBHashKey(attributeName="owningUser")
    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey
    public String getId(){
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String name) {
        this.personName = name;
    }

    @DynamoDBAttribute
    public int getAge(){
        return age;
    }
    public void setAge(int age){
        this.age = age;
    }
}
